### ISSUE TITLE
dnsclient::domain error in modules/psick/manifests/dns/dnsclient.pp

### ISSUE THREAD

**Issue by fugit** [example42/puppet-psick#52]
Using dnsclient::domain with the current version('3.5.2') of 'ghoneycutt/dnsclient' results in an error because of the domain name check in the  'ghoneycutt/dnsclient' that calls the stdlib is_domain_name which requires a string.  Search param is an easy workaround.

Code snippets below. 

**example42/puppet-psick**
```
modules/psick/manifests/dns/dnsclient.pp
# dnsclient::domain:
#   - my.domain
```

**ghoneycutt/dnsclient**
```
puppet-module-dnsclient/manifests/init.pp
...
  # Validates domain
  if is_domain_name($domain) != true {
    fail("Domain name, ${domain}, is invalid.")
  }
...
```

**puppetlabs/puppetlabs-stdlib**
```
puppetlabs-stdlib/lib/puppet/parser/functions/is_domain_name.rb
...
    # Only allow string types
    return false unless arguments[0].is_a?(String)
...
```

**Comment by alvagante** [comment]
It looks just a problem with wrong sample data, so I corrected it in the referenced commit.
Note the currently the psick::dns::dnsclient profile is basically pointless, you can include directly the dnsclient class and have the same effect.
